[package]
name = "robot"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.3.0"
hc-sr04 = "0.1.2"
rppal = "0.17.1"
fern = "0.6"
log = "0.4"
chrono = "0.4"
lcd-pcf8574 = "0.2.0"
i2cdev = "0.5.0"
lcd = "0.4.1"